on:
  workflow_dispatch:
    inputs:
      username:
        description: Github username of the person triggering the release
        default: "tboby"
        required: true
      email:
        description: Email of the person triggering the release
        default: "th.boby@gmail.com"
        required: true


name: Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        # cache: 'npm'
    - run: npm install
    - name: Set chmod
      run: chmod +x ./build.sh
    - name: Test
      run: /bin/sh ./build.sh DryRelease
    - name: upload artifact package
      uses: actions/upload-artifact@v4
      with:
        name: cwtools-fsharp-vscode-ext
        path: release/
    - name: Publish Release
      env:
        github-user: ${{ github.event.inputs.username }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        vsce-token: ${{ secrets.VSCE_TOKEN }}
        user-email: ${{ github.event.inputs.email }}
      run: dotnet run --project build -- -t Release
    - name: Publish to Open VSX Registry
      uses: HaaLeo/publish-vscode-extension@v1
      id: publishToOpenVSX
      with:
        packagePath: "./release"
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
